Create connection with MongoDB
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #15
Opened 2021-02-25 20:37 UTC by kgutka

2021-02-25 22:06 UTC, jkopyto requested changes

2021-02-25 22:06 UTC, jkopyto commented on src/index.ts
> +    const uri = `mongodb+srv://${process.env.MONGODB_USER}:${process.env.MONGODB_PASSWORD}@cluster0.u2bdz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`
A wsadź cały ten link do enva

2021-02-25 22:06 UTC, jkopyto commented on package.json
> +            "git add"
to można przy okazji usunąć

2021-02-25 22:07 UTC, jkopyto commented on package.json
> +            "git add"
w sensie samo to `"git add"`

2021-02-25 23:25 UTC, kgutka commented on src/index.ts
> +    const uri = `mongodb+srv://${process.env.MONGODB_USER}:${process.env.MONGODB_PASSWORD}@cluster0.u2bdz.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`
zrobione

2021-02-25 23:27 UTC, kgutka commented on package.json
> +            "git add"
zrobione

2021-02-28 20:11 UTC, mateuszCabala95 approved these changes

2021-03-01 10:05 UTC, merged