Add User Model
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #16
Opened 2021-02-27 14:13 UTC by kacperzolkiewski

2021-02-28 20:08 UTC, mateuszCabala95 approved these changes

2021-03-01 10:21 UTC, jkopyto requested changes

2021-03-01 10:21 UTC, jkopyto commented on src/models/User.ts
> +    password: String,
To raczej `required`

2021-03-01 10:21 UTC, jkopyto commented on src/models/User.ts
> +    dateOfBirth: String,
Też by pasowało `required`

2021-03-01 10:21 UTC, jkopyto commented on src/models/User.ts
> +    purchasedTickets: Array,
Zamiast trzymać tutaj informacje o zakupionych biletach, elegancko by wyglądała nowa kolekcja. `Purchased` albo `Transactions`. Tam by trzymane były by przechowywane informacje o zakupach (w tym o zakupionych biletach). Taka nowa kolekcja przechowywałaby `_id` użytkownika z kolekcji `Users`, który dokonał zakupu

2021-03-01 10:21 UTC, jkopyto commented on src/models/User.ts
> +    suggestedFilms: Array,
Podobnie jak wyżej. Albo jakaś osobna kolekcja, która bedzie zawierala informacje o tym na jakie filmy user kupił bilety, albo będzie to szacowane na podstawie dokonanych transakcji. Generalnie nie chcemy trzymać tej informacji na sztywno w bazie. Można to zrobić tak, że np. po zalogowaniu się użytkownika do serwisu, poleci request i np. na podstawie historii transakcji przeanalizuje i zwróci odpowiednie sugestie, które będą też zgodne z odpowiednim repertuarem

2021-03-01 10:21 UTC, jkopyto commented on package.json
>  {
wciągnięty commit :(

2021-03-01 17:26 UTC, kacperzolkiewski commented
Zdecydowaliśmy na spotkaniu, że narazie dodajemy usera bez tickets, żeby nie blokować logowania i rejestracji. Jak tylko zrobię model dla tickets to się podepnie

2021-03-01 17:46 UTC, pspaczek approved these changes
LGTM :)

2021-03-01 17:49 UTC, merged