[WIP] Feature/register-login
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #18
Opened 2021-03-01 18:08 UTC by R4fau

As yet no email, date of birth correctness nor password length/strength validation

2021-03-02 15:14 UTC, kgutka commented on .env
> +MONGO_PATH=@ds227594.mlab.com:27594/tutorial
Potrzebna nam podpięta druga bazka? Kuba zasugerował wrzucić całe URI jako zmienną środowiskową dlatego nie mieliśmy rozdzielenia tutaj na usera, hasło i path

2021-03-02 17:37 UTC, R4fau commented on .env
> +MONGO_PATH=@ds227594.mlab.com:27594/tutorial
ok, zmieniam

2021-03-02 17:45 UTC, kacperzolkiewski commented on src/models/User.ts
>  module.exports = mongoose.model("User", UserSchema)
Do usunięcia

2021-03-02 17:53 UTC, R4fau commented on src/models/User.ts
>  module.exports = mongoose.model("User", UserSchema)
ok

2021-03-03 00:14 UTC, kgutka commented on src/models/User.ts
> +// module.exports = mongoose.model("User", UserSchema)
Jeśli komentarz nie jest potrzebny - usuń

2021-03-12 15:55 UTC, jkopyto requested changes

2021-03-12 15:55 UTC, jkopyto commented on src/app.ts
> +import * as bodyParser from "body-parser"
Jest ten plik wraz z `server.ts` i jest też `index.ts`. Trzeba się określić, z którego będziemy korzystać

2021-03-12 15:55 UTC, jkopyto commented on src/app.ts
> +            console.log(`App listening on the port ${process.env.PORT}`)
zamiast console loga, skorzystajmy tu z tego pino-loggera

2021-03-12 15:55 UTC, jkopyto commented on src/authentication/authentication.controller.ts
> +import * as bcrypt from "bcrypt"
controller do folderu `routes`

2021-03-12 15:55 UTC, jkopyto commented on src/authentication/authentication.controller.ts
> +import * as express from "express"
```suggestion
import { Router, Request, Response } from "express"
```
itd.
wtedy nie musisz za każdym razem pisać `express.`

2021-03-12 15:55 UTC, jkopyto commented on src/authentication/authentication.controller.ts
> +        user.password = undefined
Najpierw przekazujesz zahashowane hasło, a teraz dajesz undefined. Czemu tak? No i pole `password` u usera jest typu `string`, więc tym bardziej, leci tutaj błąd

2021-03-12 15:55 UTC, jkopyto commented on src/authentication/authentication.controller.ts
> +            next(new UserWithThatEmailAlreadyExistsException(userData.email))
```suggestion
            throw new UserWithThatEmailAlreadyExistsException(userData.email)
```
analogicznie w pozostałych miejscach

2021-03-12 15:55 UTC, jkopyto commented on src/app.ts
> +        mongoose.connect(`mongodb://${MONGO_USER}:${MONGO_PASSWORD}${MONGO_PATH}`)
Niech całe to URI będzie pobierane z enva

2021-03-12 15:55 UTC, jkopyto commented on src/authentication/login.dto.ts
> +    @IsString()
```suggestion
    @IsString()
    @IsEmail()
```

2021-03-12 15:55 UTC, jkopyto commented on src/authentication/login.dto.ts
> +    @IsString()
```suggestion
    @IsString()
    @MinLength(8)
    @MaxLength(32)
    @IsString()
    @Matches(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#%^&*])/, {message: "Password is too weak. It must contain at least 1 lowercase letter, at least 1 uppercase leter, at least 1 numeric character and at least one special character from: !@#$%^&*"})
```

Walidacja długości oraz siły hasła

2021-03-12 15:55 UTC, jkopyto commented on src/interfaces/dataStoredInToken.ts
> +interface DataStoredInToken {
```suggestion
interface DataInToken {
```

popraw nazwe pliku na `DataInToken.interface.ts`

2021-03-12 15:55 UTC, jkopyto commented on src/interfaces/requestWithUser.interface.ts
> +import { Request } from "express"
Nazwa pliku z wielkiej

2021-03-12 15:55 UTC, jkopyto commented on src/interfaces/controller.interface.ts
> +import { Router } from "express"
Nazwa pliku z wielkiej

2021-03-12 15:55 UTC, jkopyto commented on src/interfaces/tokenData.interface.ts
> +interface TokenData {
nazwa pliku z wielkiej

2021-03-12 15:55 UTC, jkopyto commented on src/middleware/auth.middleware.ts
> +                next(new WrongAuthenticationTokenException())
throw zamiast next, analogicznie niżej

2021-03-12 15:55 UTC, jkopyto commented on src/middleware/validation.middleware.ts
> +function validationMiddleware<T>(type: any, skipMissingProperties = false): express.RequestHandler {
To na branchu Mateusza ładnie poprawiliśmy, pod kątem otypowania

2021-03-12 15:55 UTC, jkopyto commented on src/models/User.dto.ts
> +    public name: string
walidacja długości przy stringach, żeby ktoś nam pana tadeusza nie wpakował tu :P

2021-03-12 15:55 UTC, jkopyto commented on src/models/User.ts
> +        match: [/\S+@\S+\.\S+/, "is invalid"],
```
import { isEmail } from "validator"
// ... 

    email: { 
        type: String,
        trim: true,
        lowercase: true,
        unique: true,
        required: 'Email address is required',
        validate: [ isEmail, 'Please entera a valid email address ]
    }
```

2021-03-12 20:22 UTC, R4fau commented on src/authentication/login.dto.ts
> +    @IsString()
Done.

2021-03-12 20:22 UTC, R4fau commented on src/interfaces/dataStoredInToken.ts
> +interface DataStoredInToken {
OK

2021-03-12 20:22 UTC, R4fau commented on src/authentication/login.dto.ts
> +    @IsString()
ok

2021-03-12 23:04 UTC, kgutka commented on src/app.ts
> +            console.log(`App listening on the port ${process.env.PORT}`)
zrobione

2021-03-12 23:08 UTC, kgutka commented on src/authentication/authentication.controller.ts
> +import * as express from "express"
zrobione

2021-03-13 15:05 UTC, R4fau commented on src/models/User.ts
> +        match: [/\S+@\S+\.\S+/, "is invalid"],
done

2021-03-13 15:09 UTC, R4fau commented on src/authentication/authentication.controller.ts
> +        user.password = undefined
done

2021-03-13 15:16 UTC, R4fau commented on src/models/User.dto.ts
> +    public name: string
Done.

2021-03-13 16:30 UTC, kgutka commented on src/interfaces/controller.interface.ts
> +import { Router } from "express"
zrobione

2021-03-13 16:30 UTC, kgutka commented on src/interfaces/requestWithUser.interface.ts
> +import { Request } from "express"
zrobione

2021-03-13 18:51 UTC, R4fau commented on src/models/User.dto.ts
> +    public name: string
zrobione

2021-03-13 19:00 UTC, R4fau commented on src/interfaces/tokenData.interface.ts
> +interface TokenData {
ok

2021-03-13 19:01 UTC, R4fau commented on src/app.ts
> +import * as bodyParser from "body-parser"
zrobione, wszystko w index.ts

2021-03-13 19:11 UTC, R4fau commented on src/app.ts
> +        mongoose.connect(`mongodb://${MONGO_USER}:${MONGO_PASSWORD}${MONGO_PATH}`)
nieaktualne, użylliśmy metody z index.ts do łączenia z mongoDB

2021-03-13 19:12 UTC, R4fau commented on src/middleware/auth.middleware.ts
> +                next(new WrongAuthenticationTokenException())
Done.

2021-03-13 19:13 UTC, R4fau commented on src/authentication/authentication.controller.ts
> +            next(new UserWithThatEmailAlreadyExistsException(userData.email))
zrobione

2021-03-13 19:41 UTC, R4fau commented on src/middleware/validation.middleware.ts
> +function validationMiddleware<T>(type: any, skipMissingProperties = false): express.RequestHandler {
Done.

2021-03-13 19:54 UTC, R4fau commented on src/authentication/authentication.controller.ts
> +import * as bcrypt from "bcrypt"
zrobione

2021-03-13 20:10 UTC, mateuszCabala95 requested changes

2021-03-13 20:10 UTC, mateuszCabala95 commented on src/models/user/User.model.ts
> +const userModel = mongoose.model<User & mongoose.Document>("User", userSchema)
Ja bym tutaj zmienił nazwe z User  na UserModel

2021-03-13 20:10 UTC, mateuszCabala95 commented on src/routes/authentication.controller.ts
> +  public router = Router()
Myślę że można z tego robić private

2021-03-13 20:23 UTC, R4fau commented on src/routes/authentication.controller.ts
> +  public router = Router()
nie bardzo... dodałem "readonly".

2021-03-13 20:23 UTC, R4fau commented on src/models/user/User.model.ts
> +const userModel = mongoose.model<User & mongoose.Document>("User", userSchema)
zrobione

2021-03-13 20:29 UTC, mateuszCabala95 approved these changes

2021-03-13 20:31 UTC, merged