Ticket Model
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #25
Opened 2021-03-07 20:11 UTC by kacperzolkiewski

2021-03-07 20:16 UTC, mateuszCabala95 approved these changes

2021-03-11 17:04 UTC, jkopyto requested changes

2021-03-11 17:04 UTC, jkopyto commented on src/models/ticketModel/TicketModel.ts
> +    QR_CODE: {
```suggestion
    qrCode: {
```

2021-03-11 17:59 UTC, kacperzolkiewski commented on src/models/ticketModel/TicketModel.ts
> +    QR_CODE: {
done

2021-03-11 18:03 UTC, jkopyto requested changes

2021-03-11 18:03 UTC, jkopyto commented on src/models/userModel/User.interface.ts
> +export default interface IUser {
`/src/models/userModel/User.interface.ts` -> `/src/models/user/User.model.ts`

ticket analogicznie

2021-03-11 18:11 UTC, kacperzolkiewski commented on src/models/userModel/User.interface.ts
> +export default interface IUser {
done

2021-03-11 18:24 UTC, jkopyto approved these changes

2021-03-11 18:25 UTC, merged