Setup Project
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #3
Opened 2021-02-22 16:25 UTC by kacperzolkiewski

2021-02-22 17:45 UTC, adam-kostuch requested changes

2021-02-22 17:45 UTC, adam-kostuch commented on src/index.ts
> +    console.log( `server started at http://localhost:${ port }` );
When you checked the connection, you can delete those lines, we don't need them on master.

2021-02-23 10:01 UTC, jkopyto requested changes

2021-02-23 10:01 UTC, jkopyto commented on tslint.json
> +{
Po usunięciu tego i doinstalowaniu paczek utwórz pliki:

.eslintrc.js
```
module.exports = {
    root: true,
    extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:prettier/recommended",
    ],
    parser: "@typescript-eslint/parser",
    env: {
        es6: true,
        jest: true,
        node: true,
    },
    parserOptions: {
        ecmaVersion: 2020,
        sourceType: "module",
        ecmaFeatures: {
            arrowFunctions: true,
        },
    },
    plugins: ["@typescript-eslint"],
    rules: {
        quotes: ["error", "double"],
        "@typescript-eslint/explicit-function-return-type": [
            "warn",
            {
                allowExpressions: true,
            },
        ],
    },
}
```

.prettierrc.js:
```
module.exports = {
    semi: false,
    trailingComma: "all",
    singleQuote: false,
    printWidth: 120,
    tabWidth: 4
};
```

2021-02-23 13:43 UTC, kacperzolkiewski commented on tsconfig.json
> +    ]
zrobione

2021-02-23 13:43 UTC, kacperzolkiewski commented on tsconfig.json
> +        "paths": {
zrobione

2021-02-23 13:43 UTC, kacperzolkiewski commented on tsconfig.json
> +        "src/**/*"
dałem "src/*" ponieważ "src*" nie działało

2021-02-23 13:44 UTC, kacperzolkiewski commented on tslint.json
> +{
zrobione

2021-02-23 13:44 UTC, kacperzolkiewski commented on package.json
> +    "tslint": "^6.1.3",
zrobione

2021-02-23 13:44 UTC, kacperzolkiewski commented on package.json
> +    "lint": "tslint -c tslint.json -p tsconfig.json --fix",
zrobione

2021-02-23 13:44 UTC, kacperzolkiewski commented on package.json
> +  "devDependencies": {
zrobione

2021-02-23 13:44 UTC, kacperzolkiewski commented on src/index.ts
> +const port = 8080;
zrobione

2021-02-23 13:44 UTC, kacperzolkiewski commented on src/index.ts
> +    console.log( `server started at http://localhost:${ port }` );
ok

2021-02-23 13:46 UTC, kacperzolkiewski commented
Tylko nodemon coś chyba nie działa bo serwer jakby się odpala drugi raz ale strona się nie przeładowuje, nawet jak się samemu odświeży to i tak jest stara treść

2021-02-23 13:49 UTC, kgutka commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Można dodać `jest`'a do testów, dzięki temu będzie można rozpocząć testowanie

2021-02-23 14:06 UTC, jkopyto requested changes

2021-02-23 14:06 UTC, jkopyto commented on tsconfig.json
> +    "moduleResolution": "node"
```suggestion
    "moduleResolution": "node",
    "baseUrl": "./"
```

2021-02-23 14:06 UTC, jkopyto commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
To na osobnym mr. Chyba, że Kacper już zaczął

2021-02-23 14:14 UTC, jkopyto commented on src/index.ts
> +    console.log( `server started at http://localhost:${ port }` );
Tam gdzie będziemy chcieli logować jakieś rzeczy proponuję użyć `pino`

https://www.npmjs.com/package/express-pino-logger
https://www.twilio.com/blog/guide-node-js-logging

2021-02-23 18:05 UTC, kacperzolkiewski commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Jeszcze nie zacząłem. Lepiej na osobnym, a teraz aby tylko była podstawa i żeby było na czym działać

2021-02-23 18:54 UTC, kacperzolkiewski commented on tsconfig.json
> +    "moduleResolution": "node"
zrobione

2021-02-23 18:54 UTC, kacperzolkiewski commented on prettierrc.js
> +module.exports = {
zrobione

2021-02-23 18:54 UTC, kacperzolkiewski commented on tsconfig.json
> +    "moduleResolution": "node"
zrobione

2021-02-23 21:02 UTC, adam-kostuch approved these changes

2021-02-24 11:20 UTC, jkopyto commented on src/index.ts
> +    console.log( `server started at http://localhost:${ port }` );
Bedziesz dodawał to pino teraz czy robimy na to nowe issue?

2021-02-24 15:13 UTC, kacperzolkiewski commented on src/index.ts
> +    console.log( `server started at http://localhost:${ port }` );
już dodaję, to chwila roboty

2021-02-24 15:22 UTC, jkopyto approved these changes

2021-02-24 15:22 UTC, merged