Feature/payment
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #30
Opened 2021-03-14 21:33 UTC by adam-kostuch

2021-03-14 21:48 UTC, adam-kostuch commented
Closes #29

2021-03-15 14:15 UTC, kgutka approved these changes

2021-03-16 11:06 UTC, adam-kostuch commented
Closes #31

2021-03-16 11:11 UTC, kubaszajna approved these changes

2021-03-16 13:20 UTC, jkopyto requested changes

2021-03-16 13:20 UTC, jkopyto commented on src/routes/controllers/payment.controller.ts
> +  client_secret: "EESgAZabiTtNvXCZNBJLUYntYGr4gHZfNf2-o82dQ6jmoYWUuj2mqy1kSvQ-NxnwW-1Eq75A6oHEoigQ"
te rzeczy do enva

2021-03-16 13:20 UTC, jkopyto commented on src/routes/controllers/payment.controller.ts
> +    const sample_payment_json: Payment = {
To do osobnego pliku wynieś. I camelCase nazwy zmiennych

2021-03-16 13:20 UTC, jkopyto commented on src/routes/controllers/payment.controller.ts
> +/* eslint-disable @typescript-eslint/no-non-null-assertion */
bez tego

2021-03-16 13:20 UTC, jkopyto commented on src/routes/controllers/__tests__/payment/payment.spec.ts
> +/* eslint-disable @typescript-eslint/no-var-requires */
bez tego

2021-03-16 13:20 UTC, jkopyto commented on src/routes/controllers/payment.controller.ts
> +  private createPayment = (req: Request, res: Response): void => {
Otypuj dobrze każdy route. Zobacz jak to wglada np w film kontrolerze.

2021-03-16 13:20 UTC, jkopyto commented on src/routes/controllers/payment.controller.ts
> +    const execute_payment_json = {
to też można wynieść stąd

2021-03-16 17:03 UTC, jkopyto requested changes

2021-03-16 17:03 UTC, jkopyto commented on src/routes/controllers/payment.controller.ts
> +export type RequestParams1 = {
Zamień te cyfry na coś innego. Unikaj w ogóle używania cyfr w nazwach. Daj bardziej precyzyjną nazwę

2021-03-16 17:03 UTC, jkopyto commented on src/routes/controllers/__tests__/payment/payment.spec.ts
> +    const payment1 = {
Bez cyfry

2021-03-16 17:03 UTC, jkopyto commented on src/routes/controllers/__tests__/payment/payment.spec.ts
> +    const payment2 = {
Bez cyfry

2021-03-16 17:03 UTC, jkopyto commented on src/routes/controllers/__tests__/payment/payment.spec.ts
> +    const payment3 = {
Bez cyfry

2021-03-16 17:03 UTC, jkopyto commented on src/routes/controllers/__tests__/payment/payment.spec.ts
> +    const payment4 = {
Bez cyfry

2021-03-16 17:03 UTC, jkopyto commented on src/routes/controllers/__tests__/payment/__mocks__/mockResponses.ts
> +export const mockResponse1 = {
Bez cyfr w całym pliku w nazwach constów

2021-03-16 17:24 UTC, merged