Add navbar to project
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #49
Opened 2021-03-23 22:09 UTC by kgutka

Closes #48

2021-03-24 10:27 UTC, jkopyto requested changes

2021-03-24 10:27 UTC, jkopyto commented on frontend/src/components/header/navbar/Navbar.tsx
> +import { css } from "@emotion/react"
tego chyba nie potrzebujesz

2021-03-24 10:27 UTC, jkopyto commented on frontend/src/components/header/navbar/Navbar.tsx
> +        `}
```suggestion
        css={{
          backgroundColor: #000000;
        }}
```
Tak też powinno zadziałać. I żeby zachować consistency nawet przy wyobrze kolorów, polecam korzystać z kolorów dostępnych w material-ui

2021-03-24 10:27 UTC, jkopyto commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toLogin()} render={() => <Login />} />
```suggestion
          <Route path={RouteBuilder.toLogin()} render={Login} />
```

2021-03-24 10:27 UTC, jkopyto commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toMain()} render={() => <Main />} />
```suggestion
          <Route path={RouteBuilder.toMain()} render={Main} />
```
Tak też powinno zadziałać

2021-03-24 12:00 UTC, kgutka commented on frontend/src/components/header/navbar/Navbar.tsx
> +import { css } from "@emotion/react"
Zrobiłam stylowanie według dokumentacji [Emotion - String Styles](https://emotion.sh/docs/css-prop#string-styles), umknęła mi sekcja o Object Styles

Poprawione

2021-03-24 13:07 UTC, kgutka commented on frontend/src/components/header/navbar/Navbar.tsx
> +        `}
Stworzyłam osobny plik z kolorami z material-ui, które będą się powtarzać w całym projekcie

2021-03-24 13:09 UTC, kgutka commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toMain()} render={() => <Main />} />
Wyrzuca błędy

2021-03-24 13:11 UTC, kgutka commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toLogin()} render={() => <Login />} />
błąd: `Type 'FC<{}>' is not assignable to type '(props: RouteComponentProps<{ [x: string]: string | undefined; }, StaticContext, unknown>) => ReactNode'.`

2021-03-29 17:10 UTC, adam-kostuch commented on frontend/src/index.css
> +  background-color: #212121 !important;
Czy konieczne jest użycie tutaj znacznika `!important`?

2021-03-29 17:10 UTC, adam-kostuch commented on frontend/src/components/Header/Logo.tsx
> +      >
Myślałaś może o stylowaniu komponentów poprzez funkcję [makeStyles](https://material-ui.com/styles/basics/#hook-api) , która zapewnia `MaterialUi`?

2021-03-29 20:37 UTC, kgutka commented on frontend/src/components/Header/Logo.tsx
> +      >
dobry pomysł, zmieniłam to

2021-03-29 21:30 UTC, kgutka commented on frontend/src/index.css
> +  background-color: #212121 !important;
udało się pozbyć, dzięki

2021-03-30 09:38 UTC, pspaczek commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toLogin()} render={() => <Login />} />
@kgutka udało Ci się znaleźć skąd może brać się ten error ;)?

2021-03-30 09:51 UTC, pspaczek commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toLogin()} render={() => <Login />} />
@kgutka udało Ci się znaleźć skąd może brać się ten error ;)? ***dobra komentarz jednak jest aktualny

2021-03-30 10:15 UTC, pspaczek commented on frontend/src/components/Header/index.ts
> +import Header from "./Header"
Czy tworzenie takich plików ma sens? 
Rozumiem że chodzi o import 
`import Footer from "../components/Footer"` 
zamiast 
`import Footer from "../components/Footer/Footer.tsx"`

2021-03-30 11:02 UTC, pspaczek commented on frontend/src/components/Content/ContentWrapper.tsx
> +  root: {
mamy id root, sugeruję inaczej nazwać tę klasę :) może po prostu `main`

2021-03-30 11:03 UTC, pspaczek commented on frontend/src/components/Header/Header.tsx
> +          <Typography variant="h6" className={classes.title}>
to nie może być h6 ;) powinna ot być h1

2021-03-30 11:07 UTC, pspaczek commented on frontend/src/index.css
>  a {
myślę że nie powinniśmy tak nadpisywać koloru linków :)

2021-03-30 11:25 UTC, pspaczek commented on frontend/src/components/Header/Header.tsx
> +    flexGrow: 1,
<img width="1425" alt="Zrzut ekranu 2021-03-30 o 13 24 46" src="https://user-images.githubusercontent.com/12138170/112981332-4e801380-915b-11eb-9e2f-8dd8055b5068.png">
użycie `flexGrow: 1` sprawia że ta h6 ma całą szerokość :) może `marginRight: auto`

2021-03-31 13:39 UTC, kgutka commented on frontend/src/components/Header/index.ts
> +import Header from "./Header"
Tak, dokładnie, czytałam że korzystanie z barrel files jest dobrą praktyką [[link]](https://medium.com/@klauskpm/do-a-barrel-export-aa5b79b76b05), szczególnie jeśli w folderach dodamy inne pliki.
Jeśli foldery nie będą zbytnio rozbudowane to dużego znaczenia to nie robi, więc można się ich pozbyć.

2021-03-31 13:54 UTC, kgutka commented on frontend/src/components/Header/Header.tsx
> +    flexGrow: 1,
zrobione

2021-03-31 13:56 UTC, kgutka commented on frontend/src/components/Header/Header.tsx
> +          <Typography variant="h6" className={classes.title}>
zmieniłam i aby ograniczyć wielkość loga dodałam w klasie `title` atrybut `fontSize: "30px"`

2021-03-31 14:03 UTC, kgutka commented on frontend/src/index.css
>  a {
wrzuciłam styl do hooka makeStyles w pliku `Header.tsx` stworzyłam klasę `link`

2021-03-31 14:03 UTC, kgutka commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toMain()} render={() => <Main />} />
wyjaśniłam sprawę niżej

2021-04-01 10:49 UTC, pspaczek commented on frontend/src/views/App.tsx
> +          <Route path={RouteBuilder.toLogin()} render={() => <Login />} />
Dla mnie ta forma `<Route path={RouteBuilder.toLogin()}><Login /></Route>` wygląda w porządku, zastosujmy ją. 
Bardo fajny research 👍

2021-04-01 10:56 UTC, pspaczek commented on frontend/src/components/Header/index.ts
> +import Header from "./Header"
Wydaje mi się że tutaj nie do końca będzie miało to zastosowanie. Gdybyśmy tworzyli sami UiKit jako paczkę NMP to by się to fajnie sprawdziło. Moim zdaniem takim barrel files jest nadrzędny komponent jak Footer, Header etc. w nich importujesz pomniejsze komponenty i nie używasz ich poza nimi 👍 
Gdybyś stworzyła folder components i np trzymała tam button, checkbox, radio, etc... to wtedy idealny byłby taki export np. 
```
import UiAlert from './src/components/atoms/UiAlert/UiAlert.vue';
import UiBackdrop from './src/components/atoms/UiBackdrop/UiBackdrop.vue';
import UiButton from './src/components/atoms/UiButton/UiButton.vue';
import UiCheckbox from './src/components/atoms/UiCheckbox/UiCheckbox.vue';

export {
  UiAlert,
  UiBackdrop,
  UiButton,
  UiCheckbox,
};

```
wtedy działało by to tak
```
import {UiButton, UiCheckbox} from `coders-camp-kit`
```
i faktycznie nie trzeba znać ścieżek 👍

2021-04-01 11:11 UTC, pspaczek approved these changes

2021-04-01 11:11 UTC, pspaczek commented
kilka uwag w komentarzach, ale wygląda dobrze ✅

2021-04-01 22:33 UTC, merged