File structure+provider
kacperzolkiewski/CodersCamp2020.CinemaApp pull request #5
Opened 2021-02-23 20:24 UTC by kubaszajna

Added project structure and providers

2021-02-23 21:04 UTC, adam-kostuch approved these changes

2021-02-24 15:34 UTC, kacperzolkiewski approved these changes

2021-02-24 17:03 UTC, jkopyto commented
robiłeś brancha na podstawie brancha Kacpra?

2021-02-24 17:09 UTC, kubaszajna commented
tak, zrobiłem branch z tego setup Kacpra, z tego względu że na masterze było pusto i by ułatwić merge

2021-02-24 17:18 UTC, jkopyto commented
To nie jest najgorsza praktyka, ale nie w takiej formie. Otwieranie takich pull requestów, których branche nie pochodzą bezpośrednio z brancha do którego mergujemy tworzą syf w commitach. Ty wciągasz commity Kacpra jako swoje. Należałoby zesquashować wszystkie Twoje commity, otworzyć nowego brancha z mastera i cherry-picknąć commit. Jednak patrząc na to co zostało dodane, uważam że jest w projekcie za wcześnie na providery. Nie wiem czy w ogóle z nich skorzystamy. Dodatkowo, backend to nie frontend, więc nie będziemy potrzebowali plików css, scss i html. Tutaj będziemy tworzyć models, middlewares, routes, jakieś configi, itd.

2021-02-24 19:47 UTC, mateuszCabala95 commented
DObrze by było dodać od razu foldey 

- Controllers
- Models
- utils

2021-02-24 19:58 UTC, mateuszCabala95 requested changes
Providery nie będą potrzebne

2021-02-24 19:58 UTC, mateuszCabala95 commented on index.html
> +</html>
raczej plik HTML nie będzie potrzebny

2021-02-24 19:58 UTC, mateuszCabala95 commented on package.json
> +    "nodemon": "^2.0.7"
nodemon jest devDependenvy

2021-02-24 19:58 UTC, mateuszCabala95 commented on package.json
> +    "body-parser": "^1.19.0",
express ma już wbudowanego JSON parsera => express.json()

2021-02-24 19:58 UTC, mateuszCabala95 commented on package.json
> +      "git add"
According to lint-staged documentation:

`
Prior to version 10, tasks had to manually include git add as the final step. This behavior has been integrated into lint-staged itself in order to prevent race conditions with multiple tasks editing the same files. If lint-staged detects git add in task configurations, it will show a warning in the console. Please remove git add from your configuration after upgrading.
`

we should remove `git add` from `lint-staged` configuration.

2021-02-24 19:58 UTC, mateuszCabala95 commented on src/index-app.ts
> +export default init()
zbędny plik

2021-02-24 19:58 UTC, mateuszCabala95 commented on src/index.scss
> +}
zbędny plik

2021-02-25 17:04 UTC, closed without merging